import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ThemeProviders from "@/providers/ThemeProvider";
import TranslationsProvider from "@/providers/TranslationsProvider";
import initTranslations from "../i18n";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string; // Specify type as string
  };
}>) {
  const { t, resources } = await initTranslations(locale, ["default"]);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} min-h-screen dark:bg-slate-900  bg-[radial-gradient(100%_50%_at_50%_0%,rgba(0,163,255,0.13)_0,rgba(0,163,255,0)_50%,rgba(0,163,255,0)_100%)]`}
      >
        <ThemeProviders>
          <TranslationsProvider
            resources={resources}
            locale={locale}
            namespaces={["default"]}
          >
            <Header />

            {children}

            {/* <div className="absolute top-0 z-[-2] h-screen w-screen bg-white "></div> */}
          </TranslationsProvider>
        </ThemeProviders>
      </body>
    </html>
  );
}
